/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ErbStTypeahead {
    'getItemsCallback': (v: string) => Promise<any[]>;
  }
  interface ErbStTypeaheadAttributes extends StencilHTMLAttributes {
    'getItemsCallback'?: (v: string) => Promise<any[]>;
    'onTypeahead-changed'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ErbStTypeahead': Components.ErbStTypeahead;
  }

  interface StencilIntrinsicElements {
    'erb-st-typeahead': Components.ErbStTypeaheadAttributes;
  }


  interface HTMLErbStTypeaheadElement extends Components.ErbStTypeahead, HTMLStencilElement {}
  var HTMLErbStTypeaheadElement: {
    prototype: HTMLErbStTypeaheadElement;
    new (): HTMLErbStTypeaheadElement;
  };

  interface HTMLElementTagNameMap {
    'erb-st-typeahead': HTMLErbStTypeaheadElement
  }

  interface ElementTagNameMap {
    'erb-st-typeahead': HTMLErbStTypeaheadElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
